config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  mount ActionCable.server => "/cable"

  scope '(:locale)', locale: /en|br/ do
    root to: 'pages#home'
    get '/members', to: 'pages#members'
    get '/profile', to: 'pages#profile'
    get '/about', to: 'pages#about'
    # get '/contact', to: 'pages#contact'

    get 'fb/events', to: 'facebook_events#index'
    get 'fb/token', to: 'facebook_events#new'
    post 'fb/events', to: 'facebook_events#create'
    post 'fb/pull', to: 'facebook_events#pull_fb_events'

    get 'my_events', to: 'events#my_events'
    post 'nearby', to: 'events#nearby'
    # get 'invite', to: 'invites#invitation'
    get '/invite/:id/:token', to: 'invites#show_if_logged', as: 'logged_invite'
    resources :benefits, only: %i[index edit destroy] do
      resources :trades, only: %i[new create]
    end
    resources :contacts, only: %i[new create]
    resources :events do
      # get '/require', to: 'events#ask_for_ownership'
      # post '/require', to: 'events#make_it_mine'
      resources :event_categories, only: %i[create update]
      resources :invites, only: %i[create]
      # get 'invites', to: 'invites#create'
      post 'generate_link', to: 'invites#generate'
      resources :benefits, only: %i[show new create update]
      resources :checkins, only: %i[new create]
    end
    resources :event_categories, only: :destroy
    resources :invites, only: %i[show update]
    resources :places
    resources :trades, only: %i[index show]
    resources :chat_rooms, only: %i[show] do
      resources :messages, only: %i[create]
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :events , only: %i[index  show]
    end
  end
end

app/models/benefit.rb
class Benefit < ApplicationRecord
  belongs_to :event
  has_many :trades
  has_many :users, through: :trades

  validates :name, :quantity, :value_in_points, presence: true
  validates :quantity, numericality: {
    only_integer: true, greater_than_or_equal_to: 0
  }
  validates :value_in_points, numericality: {
    only_integer: true, greater_than: 0
  }, inclusion: {
    in: (1..10).map { |n| n * 500 },
    message: "%{value} is not a valid number of points"
  }
end

app/controllers/benefits_controller.rb
class BenefitsController < ApplicationController
  before_action :set_event, only: %i[new create]
  before_action :set_benefit, only: %i[edit update destroy]
  def index
    @benefits = Benefit.all.reject { |benefit| benefit.quantity.zero? }
  end

  def new
    @benefit = Benefit.new
  end

  def create
    @benefit = Benefit.new(benefit_params)
    @benefit.event = @event
    if @benefit.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def edit
    @event = @benefit.event
    if @benefit.event.user != current_user
      alert "You're not allowed"
      :back
    end
  end

  def update
    @benefit.update(benefit_params)
    redirect_to event_path(@benefit.event)
  end

  def destroy
    @benefit.destroy
    redirect_to event_path(@benefit.event)
  end
  
  private

  def benefit_params
    params.require(:benefit).permit(:name, :quantity, :value_in_points)
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_benefit
    @benefit = Benefit.find(params[:id])
  end

  def list_benefit
    @benefit = Benefit.find(params[:event.id])
  end
end

app/views/benefits/_benefits_form.html.erb
<div class="d-flex justify-content-center">
  <div class="card benefit-form-card col-12 col-md-6 p-5">
    <h6><%= t('.add_a_benefit') %></h6>
    <h2 class="mb-5"><%= @event.title %></h2>
    <%= simple_form_for [@event, @benefit] do |f| %>
      <%= f.input :name %>
      <%= f.input :quantity %>
      <%= f.input :value_in_points %>
      <%= f.button :submit, class: "btn btn-dark float-right", value: t('.update_benefit') %>
      <% if @benefit.id.present? %>
        <%= link_to t('.delete'), benefit_path(@benefit), class: 'btn btn-danger', method: :delete %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/benefits/edit.html.erb
<%= render 'benefits/benefits_form' %>

app/views/benefits/index.html.erb
<div class="container">
  <% @benefits.each do |benefit| %>
    <div class="form-columns d-flex flex-row justify-content-center">
      <div class="right-column col-12 col-md-6">
          <%= benefit.name %>
          <%= benefit.quantity %>
          <%= benefit.value_in_points %>
      </div>
    </div>
  <% end %>
</div>

app/views/benefits/new.html.erb
<%= render 'benefits/benefits_form' %>