config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  mount ActionCable.server => "/cable"

  scope '(:locale)', locale: /en|br/ do
    root to: 'pages#home'
    get '/members', to: 'pages#members'
    get '/profile', to: 'pages#profile'
    get '/about', to: 'pages#about'
    # get '/contact', to: 'pages#contact'

    get 'fb/events', to: 'facebook_events#index'
    get 'fb/token', to: 'facebook_events#new'
    post 'fb/events', to: 'facebook_events#create'
    post 'fb/pull', to: 'facebook_events#pull_fb_events'

    get 'my_events', to: 'events#my_events'
    post 'nearby', to: 'events#nearby'
    # get 'invite', to: 'invites#invitation'
    get '/invite/:id/:token', to: 'invites#show_if_logged', as: 'logged_invite'
    resources :benefits, only: %i[index edit destroy] do
      resources :trades, only: %i[new create]
    end
    resources :contacts, only: %i[new create]
    resources :events do
      # get '/require', to: 'events#ask_for_ownership'
      # post '/require', to: 'events#make_it_mine'
      resources :event_categories, only: %i[create update]
      resources :invites, only: %i[create]
      # get 'invites', to: 'invites#create'
      post 'generate_link', to: 'invites#generate'
      resources :benefits, only: %i[show new create update]
      resources :checkins, only: %i[new create]
    end
    resources :event_categories, only: :destroy
    resources :invites, only: %i[show update]
    resources :places
    resources :trades, only: %i[index show]
    resources :chat_rooms, only: %i[show] do
      resources :messages, only: %i[create]
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :events , only: %i[index  show]
    end
  end
end

app/models/invite.rb
class Invite < ApplicationRecord
  # after_create :send_invite_mail

  belongs_to :event
  belongs_to :user

  def send_invite_mail(email)
    InviteMailer.with(invite: self).invitation.deliver_now
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show update]
  before_action :set_invite, only: %i[show update show_if_logged]

  def generate_token
    char = [('a'..'z'), ('A'..'Z')].map(&:to_a).flatten
    token = (0...50).map { char[rand(char.length)] }.join
  end

  def create    
    @invite = Invite.new(invite_params)
    @invite.user = current_user
    @invite.event = Event.find(params[:event_id])
    if @invite.save
      @invite.update(token: generate_token)
      @invite.send_invite_mail(@invite.guest_email)
      flash[:notice] = "Your invite was sent to #{@invite.guest_email}"
      redirect_to event_path(@invite.event)
    else
      redirect_to event_path(@invite.event), alert: "You've already invited this person."
    end
  end

  def generate
    @invite = Invite.new(user: current_user, event: Event.find(params[:event_id]), token: generate_token)
    if @invite.save
      respond_to do |format|
        format.html { redirect_to event_path(@invite.event) }
        format.js
      end
    else
      redirect_to event_path(@invite.event)
    end
  end

  ###########################################################################
  # action created just to test the email front-end
  # def invitation
    # @invite = Invite.all.select { |event| event.status = 'pending'}.sample
  # end
  ############################################################################

  #############################
  # def guest
  #   @invite = Invite.new(invite_params)
  #   @invite.event = Event.find(params[:event_id])
  #   @invite.send_invite_mail(@invite.guest_email)
  #   redirect_to event_path(@invite.event)
  # end

  def new
  end

  def show
    @event = @invite.event
    redirect_to root_path, alert: 'Invalid invite.' unless @invite.token == params[:token]
    redirect_to root_path, alert: 'You cannot accept your own invite.' if @invite.user == current_user
    redirect_to root_path, alert: 'Invite already accepted.' if @invite.status == 'accepted'
  end

  def show_if_logged
    @event = @invite.event
    redirect_to invite_path(@invite, token: params[:token])
  end

  def update
    if @invite.status == 'accepted'
      redirect_to event_path(@invite.event), alert: 'Invite already accepted.'
      return
    end
    @invite.update(status: 'accepted', guest_name: current_user.name, guest_email: current_user.email)
    @invite.user.update(points: @invite.user.points + 15)
    redirect_to event_path(@invite.event)
  end
  
  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_invite
    @invite = Invite.find(params[:id])
  end

  def invite_params
    params.require(:invite).permit(:guest_name, :guest_email)
  end
end

app/views/invites/generate.js.erb
inviteBtn = document.getElementById('invite-with-link-button')
link = document.getElementById('invite-link');

link.dataset.clipboardText = window.location.origin + "/" + "/invites/" + "<%= @invite.id %>" + "?token=" + "<%= @invite.token %>";
console.log(link.dataset.clipboardText);
link.classList.remove('d-none');
inviteBtn.remove();

link.addEventListener('click', e => {
    link.innerHTML = "<%= t('.copied') %>"
    link.classList.remove('btn-success');
    link.classList.add('btn-primary');
})

app/views/invites/show.html.erb
<% content_for :meta_title, "#{@invite.event.title} #{t('.is_on')} #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, t('.meta_description') %>
<% content_for :meta_image, @invite.event.cover %>
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="card invite-card col-12 col-sm-6 p-4">
      <div class="card-title text-center">
        <h2><%= @invite.user.name %></h2>
        <p><%= t('.has_invited') %></p>
        <h1><%= @event.title %></h1>
        <p><%= @event.start_time.strftime('%d.%m.%Y %H:%M') %></p>
        <p><%= @event.places.present? ? @event.places.first.name : '' %></p>
        <%= simple_form_for @invite do |f| %>
          <% if current_user.present? %>
            <%= f.submit value: t('.accept'), class: 'btn btn-outline-dark' %>
          <% else %>
            <%= link_to  t('.login_to_accept'), logged_invite_path(@invite, @invite.token), class: 'btn btn-outline-dark' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>