config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  mount ActionCable.server => "/cable"

  scope '(:locale)', locale: /en|br/ do
    root to: 'pages#home'
    get '/members', to: 'pages#members'
    get '/profile', to: 'pages#profile'
    get '/about', to: 'pages#about'
    # get '/contact', to: 'pages#contact'

    get 'fb/events', to: 'facebook_events#index'
    get 'fb/token', to: 'facebook_events#new'
    post 'fb/events', to: 'facebook_events#create'
    post 'fb/pull', to: 'facebook_events#pull_fb_events'

    get 'my_events', to: 'events#my_events'
    post 'nearby', to: 'events#nearby'
    # get 'invite', to: 'invites#invitation'
    get '/invite/:id/:token', to: 'invites#show_if_logged', as: 'logged_invite'
    resources :benefits, only: %i[index edit destroy] do
      resources :trades, only: %i[new create]
    end
    resources :contacts, only: %i[new create]
    resources :events do
      # get '/require', to: 'events#ask_for_ownership'
      # post '/require', to: 'events#make_it_mine'
      resources :event_categories, only: %i[create update]
      resources :invites, only: %i[create]
      # get 'invites', to: 'invites#create'
      post 'generate_link', to: 'invites#generate'
      resources :benefits, only: %i[show new create update]
      resources :checkins, only: %i[new create]
    end
    resources :event_categories, only: :destroy
    resources :invites, only: %i[show update]
    resources :places
    resources :trades, only: %i[index show]
    resources :chat_rooms, only: %i[show] do
      resources :messages, only: %i[create]
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :events , only: %i[index  show]
    end
  end
end

app/views/shared/_event_card.html.erb
<div class="my-3 horizontal-scroll">
  <% events.each do |event| %>
  
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-3 d-inline-block">
      
      <%= link_to event do %>
          <div class="city-tag d-flex align-items-center">
            <i class="fas fa-map-marker-alt mr-2"></i>
            <%= event.places[0].city %> / <%= event.places[0].state %>
          </div>
        <div class="card-size card-trip">
          <% placeholder_url = "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?ixlib=rb-1.2.1&auto=format&fit=crop&w=2467&q=80" %>
          <%= image_tag event.cover.presence ? event.cover : placeholder_url %>
          <div class="card-trip-infos">
            <div class="event-card-header px-2 d-flex align-items-start">
              <div class="flex-column mr-3">
                <p class='start-time-red-month'><%= event.start_time.strftime('%b').upcase %></p>
                <h5 class='start-time-day'><%= event.start_time.strftime('%d') %></h5>
              </div>
              <div class="d-flex flex-column">
                <h2><%= truncate(event.title, length: 42) %></h2>
                <!-- <p><%#= event.places.first.name %></p> -->
              </div>
            </div>
          </div>
          <div class="d-flex event-card-event-description align-items-end px-3">
            <p><%= truncate(event.description, length: 80) %></p>
          </div>
        </div>
      <% end %>
      
    </div>
  <% end %>
</div>

app/views/shared/_event_card_index.html.erb
<div class="row d-flex">
  <% events.each do |event| %>
    <div class="col-md-6 col-xl-4 mb-3 index-event-card" data-event-id="<%= event.id %>">
      <%= link_to event do %>
        <div class="city-tag d-flex align-items-center">
          <i class="fas fa-map-marker-alt mr-2"></i>
            <%= event.places[0].city %> / <%= event.places[0].state %>
        </div>
        <div class="card-size-index card-trip-index">
          <% placeholder_url = "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?ixlib=rb-1.2.1&auto=format&fit=crop&w=2467&q=80" %>
          <%= image_tag event.cover.presence ? event.cover : placeholder_url %>
          <div class="card-trip-infos-index">
            <div class="d-flex justify-content-between">
              <div class="flex-column">
                <h2><%= truncate(event.title, length: 40) %></h2>
                <p class='mt-1'><%= event.places.first.name %></p>
              </div>
              <div class="flex-column">
               <p class='start-time-red-month-index'><%= event.start_time.strftime('%b').upcase %></p>
               <h5 class='start-time-day-index'><%= event.start_time.strftime('%d') %></h5>
              </div>

            </div>
            <!-- <div class="d-flex justify-content-between align-items-end mt-2"> -->
              <!-- <p><%#= truncate(event.description, length: 80) %></p> -->
              <!-- <div class="flex-column"> -->
              <!-- </div> -->
            <!-- </div> -->
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert" id='flash-notice'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible" role="alert" id='flash-alert'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer bg-dark d-flex flex-column justify-content-between">
  <div class="d-flex flex-column justify-content-between" id="columns">

    <div class="d-flex flex-column align-items-center" id="footer-social-links">
      <p><%= t('.follow_us_on') %></p>
      <div class="d-flex justify-content-center">
        <a href="https://github.com/jucaesmanhoto/yoohood-app" target="_blank"><i class="fab fa-github p-1"></i></a>
        <a href="https://www.instagram.com/yoohood.fun/" target="_blank"><i class="fab fa-instagram p-1"></i></a>
        <a href="https://www.facebook.com/yoohood/" target="_blank"><i class="fab fa-facebook p-1"></i></a>
        <a href="https://twitter.com/yoohoodco" target="_blank"><i class="fab fa-twitter p-1"></i></a>
      </div>
    </div>

    <div class="d-flex flex-row align-items-center" id="footer-pages">
      <div class="footer-pages-column text-end">
        <ul>
          <a href="">
            <li><%= link_to t('.cookies'), new_contact_path %> </li>
          </a>
          <a href="">
            <li><%= link_to t('.help_center'), new_contact_path %></li>
          </a>
          <li><%= link_to t('.contact_us'), new_contact_path %></li>
        </ul>
      </div>
      <div class="footer-pages-column text-start">
        <ul>
          <li><%= link_to t('.about_us'), about_path %></li>
          <a href="">
            <li><%= link_to t('.legal'), new_contact_path %></li>
          </a>
          <a href="">
            <li><%= link_to t('.privacy_police'), new_contact_path %></li>
          </a>
        </ul>
      </div>
    </div>

  </div>

  <div class="footer-copyright row justify-content-center mx-0 my-2">
    <p><%= t('.copyright') %></p>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark bg-dark navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand mx-4" do %>
    <%= image_tag "logo_yoohood_alta.png", alt: 'yoohood logotype' %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item d-flex justify-content-end">
          <%= simple_form_for 'coordinates', url: nearby_path do |f| %>
            <%= f.hidden_field :latitude, id: 'latitude-input' %>
            <%= f.hidden_field :longitude, id: 'longitude-input'%>
            <%= f.submit t('.nearby'), class: "nav-link d-none text-right", id: 'nearby-button' %>
          <% end %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" href="/my_events"><%= t('.my_events') %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/events"><%= t('.all_events') %></a>
          </li>
        <% end %>

        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <% placeholder = current_user.facebook_picture_url ? current_user.facebook_picture_url : "https://www.wittenberg.edu/sites/default/files/2018-10/nouser_0.jpg" %>
            <%= image_tag current_user.photo.url ? current_user.photo.url : placeholder , class: "avatar dropdown-toggle ml-3", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

              <!-- items to implement -->
              <!-- <%= link_to root_path, class: 'dropdown-item' do %>
                <div class="d-flex justify-content-between align-items-center">
                  <%= t('.invitations') %>
                  <i class="fas fa-ticket-alt"></i>
                </div>
              <% end %>
              <div class="dropdown-divider"></div>
              <%= link_to root_path, class: 'dropdown-item' do %>
                <div class="d-flex justify-content-between align-items-center">
                  <%= t('.rewards') %>
                  <i class="fas fa-trophy"></i>
                </div>
              <% end %>
              <div class="dropdown-divider"></div>
              <%= link_to root_path, class: 'dropdown-item' do %>
                <div class="d-flex justify-content-between align-items-center">
                  <%= t('.settings') %>
                  <i class="fas fa-cog"></i>
                </div>
              <% end %> 
              <div class="dropdown-divider"></div>-->
              <%= link_to profile_path, class: 'dropdown-item' do %>
                <div class="d-flex justify-content-between align-items-center">
                  <%= t('.my_profile') %>
                  <i class="fas fa-user"></i>
                </div>
              <% end %>
              <div class="dropdown-divider"></div>
              <%= link_to destroy_user_session_path, class: 'dropdown-item', method: :delete do %>
                <div class="d-flex justify-content-between align-items-center">
                  <%= t('.log_out') %>
                  <i class="fas fa-sign-out-alt"></i>
                </div>
              <% end %>
            </div>
          </li>
        <% elsif @page_name != 'members' %>
          <li class="nav-item">
            <%= link_to t('.members'), members_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
</div>

app/views/shared/_sign_in.html.erb
<div class="container devise-forms">
  <div class="card">
    <div class="card-title text-center mt-4">
      <h2>Log in</h2>
    </div>
    <div class="card-body mt-n4">
      <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
        <div class="form-inputs">
          <%= f.input :email,
                      required: false,
                      autofocus: true,
                      input_html: { autocomplete: "email" } %>
          <%= f.input :password,
                      required: false,
                      input_html: { autocomplete: "current-password" } %>
          <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
        </div>
        <div class="mt-4">
          <div class="form-actions">
            <%= f.button :submit, "Log in", class: 'btn btn-primary w-100' %>
            <%= render "devise/shared/links" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_sign_up.html.erb
<div class="container devise-forms">
  <div class="card">
    <div class="card-title text-center mt-4">
      <h2>Sign up</h2>
    </div>
    <div class="card-body mt-n4">
      <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.input :name,
                      required: true,
                      autofocus: true,
                      input_html: { autocomplete: "name" }%>
          <%= f.input :email,
                      required: true,
                      input_html: { autocomplete: "email" }%>
          <%= f.input :password,
                      required: true,
                      hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                      input_html: { autocomplete: "new-password" } %>
          <%= f.input :password_confirmation,
                      required: true,
                      input_html: { autocomplete: "new-password" } %>
        </div>
        <div class="form-actions">
          <%= f.button :submit, "Sign up", class: 'btn btn-primary w-100' %>
        </div>
      <% end %>
    </div>
  </div>
</div>