config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  mount ActionCable.server => "/cable"

  scope '(:locale)', locale: /en|br/ do
    root to: 'pages#home'
    get '/members', to: 'pages#members'
    get '/profile', to: 'pages#profile'
    get '/about', to: 'pages#about'
    # get '/contact', to: 'pages#contact'

    get 'fb/events', to: 'facebook_events#index'
    get 'fb/token', to: 'facebook_events#new'
    post 'fb/events', to: 'facebook_events#create'
    post 'fb/pull', to: 'facebook_events#pull_fb_events'

    get 'my_events', to: 'events#my_events'
    post 'nearby', to: 'events#nearby'
    # get 'invite', to: 'invites#invitation'
    get '/invite/:id/:token', to: 'invites#show_if_logged', as: 'logged_invite'
    resources :benefits, only: %i[index edit destroy] do
      resources :trades, only: %i[new create]
    end
    resources :contacts, only: %i[new create]
    resources :events do
      # get '/require', to: 'events#ask_for_ownership'
      # post '/require', to: 'events#make_it_mine'
      resources :event_categories, only: %i[create update]
      resources :invites, only: %i[create]
      # get 'invites', to: 'invites#create'
      post 'generate_link', to: 'invites#generate'
      resources :benefits, only: %i[show new create update]
      resources :checkins, only: %i[new create]
    end
    resources :event_categories, only: :destroy
    resources :invites, only: %i[show update]
    resources :places
    resources :trades, only: %i[index show]
    resources :chat_rooms, only: %i[show] do
      resources :messages, only: %i[create]
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :events , only: %i[index  show]
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :places, dependent: :destroy
  has_many :benefits, dependent: :destroy
  belongs_to :user
  has_many :invites, dependent: :destroy
  has_many :event_categories, dependent: :destroy
  has_many :categories, through: :event_categories, dependent: :destroy
  has_many :checkins
  has_many :event_fb_event_admins
  has_many :fb_event_admins, through: :event_fb_event_admins
  attr_accessor :adm_token

  include PgSearch::Model
  pg_search_scope :search_by_event_and_artist,
                  against: %i[title description],
                  using: {
                    tsearch: { prefix: true } # <-- now `superman batm` will return something!
                  }
  # pg_search_scope :search_by_city_and_zip_code,
  #                 associated_against: { places: %i[city] },
  #                 using: {
  #                   tsearch: { prefix: true } # <-- now `superman batm` will return something!
  #                 }
  accepts_nested_attributes_for :event_categories
  accepts_nested_attributes_for :places
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::V1::BaseController
    before_action :set_event, only: %i[show]
        
    def index
      @events = policy_scope(Event)
    end

    def show
        
    end

    private

    def set_event
        @event = Event.find(params[:id])
        authorize @event
    end
    
    
  end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show nearby]
  before_action :set_event, only: %i[show edit update ask_for_ownership make_it_mine]

  def index
    events_by_city = params[:city].present? ? Place.near(params[:city], 10).map(&:event) : []
    # @events = @events.search_by_city_and_zip_code(params[:city]) if params[:city].present?
    events_by_title = params[:title_description].present? ? Event.search_by_event_and_artist(params[:title_description]) : []

    if params[:date].present?
      date = Date.parse(params[:date])
      events_by_date = Event.where('start_time < ? AND end_time > ?', date.beginning_of_day, date.end_of_day)
    else
      events_by_date = []
    end
    @events = (events_by_city + events_by_title + events_by_date).uniq
    @events = Event.all if @events.count.zero?
    @events = @events.reject { |event| event.end_time <= Time.now.getutc }.sort { |a, b| a.start_time <=> b.start_time }
    @markers = @events.map do |event|
      {
        lat: event.places.first.latitude,
        lng: event.places.first.longitude,
        image_url: helpers.asset_url('yo_pin-01.png'),
        event_id: event.id
      }
    end
  end

  def show
    @invite = Invite.new
    @trade = Trade.new
    @markers = [
      {
        lat: @event.places.first.latitude,
        lng: @event.places.first.longitude,
        image_url: helpers.asset_url('yo_pin-01.png'),
        event_id: @event.id
      }
    ]
  end

  # REQUIRE EVENTS
  def ask_for_ownership
  end

  def make_it_mine
    @event.update(user: current_user)
    redirect_to event_path(@event)
  end

  def my_events
    user_events = Event.all.select { |event| event.user == current_user }
    @past_events = user_events.select { |event| event.end_time <= DateTime.now }.sort { |a, b| a.start_time <=> b.start_time }
    @events = (user_events - @past_events).sort { |a, b| a.start_time <=> b.start_time }.reverse
  end

  def new
    @page_name = 'Register an event'
    @event = Event.new
  end

  def nearby
    lat_lng = params['coordinates']
    user_position = [lat_lng[:latitude].to_f, lat_lng[:longitude].to_f]
    updated_events = Event.all.reject { |event| event.end_time < DateTime.now }
    @nearby_events = updated_events.reject { |event| distance(user_position, [event.places[0].latitude, event.places[0].longitude]) > 10 }
                                   .sort { |a, b| a.start_time <=> b.start_time }
    @markers = @nearby_events.map do |event|
      {
        lat: event.places.first.latitude,
        lng: event.places.first.longitude,
        image_url: helpers.asset_url('yo_pin-01.png'),
        event_id: event.id
      }
    end
  end

  def create
  end

  def edit
  end

  def categories_update
    @event.categories = []
    params[:event][:category_ids].each do |id|
      next if id.empty?

      @event.categories << Category.find(id)
    end
    redirect_to my_events_path(current_user)
  end

  def update
    categories_update
  end

  def destroy
  end

  private

  def distance(loc1, loc2)
    rad_per_deg = Math::PI / 180 # PI / 180
    rkm = 6371                  # Earth radius in kilometers
    rm = rkm * 1000             # Radius in meters

    dlat_rad = (loc2[0] - loc1[0]) * rad_per_deg # Delta, converted to rad
    dlon_rad = (loc2[1] - loc1[1]) * rad_per_deg

    lat1_rad, lon1_rad = loc1.map { |i| i * rad_per_deg }
    lat2_rad, lon2_rad = loc2.map { |i| i * rad_per_deg }

    a = Math.sin(dlat_rad / 2)**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * Math.sin(dlon_rad / 2)**2
    c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))

    rkm * c # Delta in kilometers
  end

  def set_event
    if params[:event_id].present?
      @event = Event.find(params[:event_id])
    else
      @event = Event.find(params[:id])
    end
  end
end

app/views/events/_benefit_card.html.erb
<div class="container">
  <div class="row justify-content-center">
    <% @event.benefits.each do |benefit| %>
      <%# next if benefit.quantity.zero? %>

      <%= link_to current_user == @event.user ? edit_benefit_path(benefit) : new_benefit_trade_path(benefit), class: "benefit-card card col-lg-4 mx-2 flex-row card-title justify-content-between", current_user == @event.user ? '' : "data-toggle" => "modal", "data-target" => "#benefit-#{benefit.id}-modal" do %>
        <div class="benefit-quantity"><%= benefit.quantity %> ud.</div>
        <div class="benefit-name"><%= benefit.name %></div>
        <div class="benefit-value"><span><%= benefit.value_in_points %></span>pts</div>
      <% end %>


      <div class="modal" tabindex="-1" role="dialog" id="benefit-<%= benefit.id %>-modal" >
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">
                <h3><%= @event.title %></h3>
              </h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>

            <div class="d-row border flex-column p-2">
              <% if current_user.present? && current_user.points >= benefit.value_in_points%>
                <span class="badge badge-primary p-2 float-right">
                  <%= t('.balance') %>
                  <h3 class="mb-0 mt-2"><%= current_user.points %></h3> <%= t('.points') %>
                </span>
              <% else %>
                <span class="badge badge-danger p-2 float-right">
                  <%= t('.balance') %>
                  <h3 class="mb-0 mt-2"><%= current_user.present? ? current_user.points : '' %></h3> <%= t('.points') %>
                </span>
              <% end %>
            </div>

            <% if current_user.present? && current_user.points >= benefit.value_in_points %>
              <!-- Tells user if befit is not avaiable -->
              <% if benefit.quantity.zero? || @event.start_time < DateTime.now %>
                <div class="modal-body p-4">
                  <h4 class="mb-4"><%= t('.unavailable_benefit') %></h4>
                </div>
              <!-- Show the trade form if benefit is availabe -->
              <% else %>
                <%= simple_form_for [benefit, @trade] do |f| %>
                  <div class="modal-body">
                   <div class="d-flex justify-content-between">
                    <p><%= benefit.quantity %></p>
                    <p><%= benefit.name %></p>
                    <p><%= benefit.value_in_points %> pts./each</p>
                   </div>
                    <% max_reclaim = benefit.quantity >= (current_user.points / benefit.value_in_points) ? (current_user.points / benefit.value_in_points) : benefit.quantity %>
                    <%= f.input :quantity, as: :select, collection: (1..max_reclaim).to_a, include_blank: false %>
                  </div>
                  <div class="modal-footer">
                    <%= f.submit t('.redeem'), class: "btn btn-dark align-items-center"%>
                  </div>
                <% end %>
              <% end %>
            <% else %>
              <% if current_user.nil? %>
                <div class="modal-body p-4">
                  <h4 class="mb-4"><%= t('.not_logged') %></h4>
                  <%= link_to t('.sign_in'), new_user_session_path, class: 'btn btn-primary' %>
                </div>
              <% else %>
                <div class="modal-body p-4">
                  <h4 class="mb-4"><%= t('.not_enough_points') %></h4>
                  <p><%= t('.invite_friends') %></p>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/events/_categories.html.erb
<div class="form-group">
    <% @event.categories.each do |category| %>
      <span class="category-choice" style="background-color: <%= category.color_hex  %>" data-category-id="<%= category.id %>" >
        <%= category.name %>
        <%= link_to 'x', event_category_path(id: EventCategory.find_by(event: @event, category: category).id, event_id: @event.id), method: :delete, remote: true %>
      </span>
    <% end %>

    <div class="d-flex justify-content-end">
      <%= simple_form_for @event, url: event_event_category_path(@event), remote:true do |f| %>
        <%= f.input :categories, as: :select, collection: Category.all, input_html: { class: 'select-css' } %>
        <%= f.button :submit, t('.update'), class: 'btn btn-primary mb-2' %>
      <% end %>
    </div>
</div>

app/views/events/ask_for_ownership.html.erb
<div class="container mb-5">
  <div class="row justify-content-center">
    <div class="card require-card col-12 col-sm-6 pt-3 px-4">
      <div class="card-title">
        <p><%= t('.are_you') %></p>
        <h1 class="text-center"><%= @event.title %>?</h1>
        <div class="d-flex justify-content-between mt-4">
          <%= link_to t('.y'), event_require_path(@event), class: 'btn btn-dark', method: 'POST' %>
          <%= link_to t('.cancel'), :back, class: 'btn btn-dark' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/facebook_events.html.erb
<div class="container padding-top-page-content">
  <h1><%= t('.facebook_events') %></h1>
  <% if @events.count > 0 %>
    <%= render 'facebook_events/fb_event_card', events: @events %>
  <% else %>
    <div class="col-sm-12 col-md-6">
      <h2><%= t('.no_available_events') %></h2>
    </div>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-8 index-events-frame">
      <% if @events.count.zero? %>
        <h1><%= t('.no_events') %></h1>
      <% else %>
        <%= render 'shared/event_card_index', events: @events %>
      <% end %>
    </div>
    <div class="col-12 col-md-4">
      <!-- MAPBOX MAP: -->
      <!-- <div class="map" id="map1" data-markers="<%= @markers.to_json %>"data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>" style="flex: 0 0 370px; height: 80vh; width: 100%; position: sticky !important; margin-left: 20px; margin-top: 45px; margin-bottom: 45px"></div> -->

      <!-- GOOGLE MAPS MAP: -->
      <div id="gmap" class="d-flex justify-content-center align-items-center mb-3" style="height: 80vh; background-color: #0052f7;" data-markers="<%= @markers.to_json %>">
        <%= t('.loading_map') %>
      </div>
    </div>
  </div>
</div>

app/views/events/my_events.html.erb
<div class="container">
    <%= render 'shared/event_card', events: @events %>
    <h2><%= t('.past_events') %></h2>
    <%= render 'shared/event_card', events: @past_events %>
</div>

app/views/events/nearby.html.erb
<div class="container">
    <div class="row my-5">
        <div id="gmap-nearby" class="gmap col-12 col-md-6 d-flex justify-content-center align-items-center mb-3" style="height: 80vh; background-color: #0052f7;" data-markers="<%= @markers.to_json %>">
            <%= t('.loading_map') %>
        </div>
        <div class="col-12 col-md-6 nearby-event-index">
            <% if @nearby_events.count == 0 %>
                <h2 class="text-center"><%= t('.no_events') %></h2>              
            <% else %>
                <%= render 'shared/event_card_index', events: @nearby_events %>
            <% end %>
        </div>
    </div>
</div>

app/views/events/show.html.erb
<% content_for :meta_title, "#{@event.title} #{t('.is_on')} #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, t('.meta_description') %>
<% content_for :meta_image, @event.cover %>

<div class="event-show-page container">
  <div class="card-event-show">
    <div class="card-info-show">
      <div id="cover-and-map">
        <% placeholder_url = "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?ixlib=rb-1.2.1&auto=format&fit=crop&w=2467&q=80" %>
        <%= image_tag @event.cover.presence ? @event.cover : placeholder_url, alt: "event cover" %>
        <i id="show-map" class="fas fa-map-marked-alt"></i>
        <i id="hide-map" class="fas fa-times"></i>
        <div id="gmap-show" class="gmap d-none d-md-inline-flex" data-markers="<%= @markers.to_json %>"></div>
      </div>
      <% if false %>
      <%= render 'categories' %>
      <% elsif false %>
      <% @event.categories.each do |category| %>
      <span class="category-choice" style="background-color: <%= category.color_hex  %>">
        <%= category.name %>
      </span>
      <% end %>
      <% end %>
      <div class="card-body">
        <div class="card-title d-flex flex-column">
          <div class="d-flex justify-content-between align-items-center">
            <div class="mb-3 flex-column flex-grow-0" style="padding: 5px; margin-right: 30px; margin-left: 5px">
              <p class='start-time-red-month-show'><%= @event.start_time.strftime('%b').upcase %></p>
              <h5 class='start-time-day-show'><%= @event.start_time.day %></h5>
            </div>
            <div class="flex-column flex-grow-1">
              <h2 class="font-weight-bold title-size mr-4">
                <%= @event.title %>
              </h2>
            </div>
            <div class="d-flex ml-2 qr-checkin flex-grow-0">
              <% if (@event.start_time < DateTime.now) && (@event.end_time > DateTime.now) %>
              <%= image_tag('QR-code.svg', style: 'width: 30px;') %>
              <a class="small text-dark" , style="white-space: nowrap; padding-left: 4px"
                href="https://qrcodescan.in"><%= t('.check_in') %></a>
              <% end %>
            </div>
          </div>
          <div class="benefits">
            <%= render 'benefit_card' %>
          </div>
          <% if @event.user == current_user %>
          <%= link_to t('.add_a_benefit'), new_event_benefit_path(@event), class: 'btn btn-dark' %>
          <% end %>
          <div class="row justify-content-between">
            <% if current_user.present?%>
            <div class="col-12 col-md-6">
              <button class="btn btn-block btn-success mt-3" data-toggle="modal"
                data-target="#inviteModal"><%= t('.invite_by_mail') %></button>
            </div>
            <div class="col-12 col-md-6">
              <%= simple_form_for [@event, @invite], url: event_generate_link_path(@event), remote: true do |f|%>
              <%= f.submit value: t('.invite_with_link'), class: "btn btn-block btn-success mt-3", id: 'invite-with-link-button' %>
              <% end %>

              <div id="invite-link" class="btn btn-block btn-success mt-3 d-none text-center"
                data-clipboard-action="copy" data-clipboard-text=''>
                <i class="fa fa-clipboard mr-2" aria-hidden="true"></i>
                <%= t('.copy_to_clipboard') %>
              </div>
            </div>

            <% else %>
            <div class="col-12">
              <%= link_to t('.become_a_yoder'), members_path, class: "btn btn-block btn-primary mt-3" %>
            </div>
            <% end %>
          </div>
          <div class="d-flex flex-row my-4 text-black-50 align-items-center">
            <i class="far fa-clock" style="margin-right: 10px; padding-top: 3px"></i>
            <div class="flex-column">
              <p class='time-show'><%= t('.start') %><%= l(@event.start_time, format: :event_show_card) %></p>
              <p class='time-show'><%= t('.end') %><%= l(@event.end_time, format: :event_show_card) %></p>
            </div>
          </div>
          <div class="d-flex text-black-50">
            <i class="fas fa-map-marker-alt" style="margin-right: 10px; padding-top: 3px"></i>
            <p class="address-bottom"><%= @event.places.first.name %></p>
          </div>
          <p class="address-bottom address-side text-black-50"><%= @event.places.first.address %></p>
          <p class="address-side text-black-50"><%= @event.places.first.city %></p>
          <div class="d-flex text-black-50">
            <% if @event.ticket_uri.present? %>
            <i class="fas fa-ticket-alt" style="margin-right: 10px; padding-top: 3px"></i>
            <%= link_to 'Tickets', @event.ticket_uri, target: "_blank", class: 'text-black-50' %>
            <% end %>
          </div>
        </div>
        <div class="divider mb-3" style="height: 3px; width: 100%; background-color: #000;"></div>
        <div class="event-description p-2">
          <p class="text-dark"><%= @event.description %></p>
        </div>
        <%= link_to t('.back'), events_path, class: "ml-3 my-4 btn btn-outline-dark float-left" %>
        <%= link_to t('.event_admin'), new_contact_path, class: "mr-3 my-4 btn btn-outline-dark float-right" %>
      </div>
    </div>

    <!-- INVITE MODAL -->
    <div class="modal" tabindex="-1" role="dialog" id="inviteModal">
      <div class="modal-dialog" role="document">
        <%= simple_form_for @invite, url: event_invites_path(@event), method: :post do |f| %>
        <div class="modal-content invite-box">
          <div class="modal-header">
            <div class="d-flex-flex-column">
              <p class="modal-title text-black"><%= t('.invite_a_friend_to') %></p>
              <h2 class="modal-title text-align-center text-black"><%= @event.title %></h2>
            </div>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <!--  Need to put presence true -->
            <%= f.input :guest_name, placeholder: "John Doe" %>
            <%= f.input :guest_email, placeholder: "johndoe@gmail.com" %>
          </div>
          <div class="modal-footer">
            <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
            <!-- Make button smaller -->
            <%= f.submit t('.submit'), class: "btn btn-dark align-items-center"%>
          </div>
          <% end %>
        </div>
      </div>
    </div>